# Generated by Django 5.1.1 on 2024-09-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedulingModels',
            new_name='ProductModel',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agenda.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduling',
            name='client',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
