# Generated by Django 5.1.1 on 2024-09-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_schedulingmodels_productmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='expiration',
            field=models.IntegerField(default=1),
        ),
    ]
