# Generated by Django 5.1.1 on 2024-10-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
